config/routes.rb
WishPanda3::Application.routes.draw do
  resources :contests


  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/tweet.rb
class Tweet
  include Mongoid::Document
  field :user_id, type: Integer
  field :tweet_text, type: String
  field :screen_name, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :email, type: String
  field :picture, type: String
  attr_accessible :provider, :uid, :name, :email
  validates_presence_of :name
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.picture = auth['info']['image']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

  def update_picture(auth)
    self.picture = auth['info']['image']
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
# Reset the session after successful login, per
# 2.8 Session Fixation – Countermeasures:
# http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

    def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<div class="content pure-g-r">
    <div class="splash pure-u-1">
        <div class="pure-g-r">
            <div class="pure-u-11-12">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                    	<%= image_tag("200pxWPlogo.png", :alt => "Wishing Panda") %> 
                       <% if current_user %>
                        Welcome to WishPanda, <%= current_user.name%>
                        <%end%>  
                    </h1>

                    <h2 class="splash-subhead" style="text-align:right">
                    	WishPanda. Makin Contests Legit.

                    </h2>

              
                    <div class="pure-u-1" style="text-align:right;">
                        <%= link_to "Find A Contest!", contests_path,  {:style=>'color:#FFFFFF;', :class => "pure-button primary-button"} %>
                     </div> 
                 
                </div>
            </div>
        </div>
    </div>

    <div class="content pure-u-1">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-4">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Placeholder image for example.">
                </div>
            </div>

            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Featured Contest</h4>

                    <h3>Win A Used Water Bottle</h3>
                    <p>
                        Description on how to enter the contest: Tweet the phrase "Panda'a saliva 2013" For a chance to win! 
                    </p>
                </div>
            </div>
        </div>
<div class="l-box">
<h1 class="spash-head"> Start Your Own Contest </h1> 
</div> 
        <div class="pure-g-r">
            <div class="pure-u-1-4">
                <div class="l-box">
                    <h3>Step 1: Make A Contest</h3>
                    <p>
                        Tell WishPanda what hashtag(s) and keywords(s) you would like to collect Tweets about and pick a prize to handout! 
                    </p>
                </div>
            </div>

            <div class="pure-u-1-3">
                <div class="l-box">
                    <h3>Step 2: Hand out your prize!</h3>
                    <p>
                        Picking a winner is simple and straight-forward to deliver your prize. WishPanda will notify the winner(s) so you can deliver the prize!
                    </p>
                </div>
            </div>

            <div class="pure-u-1-3">
                <div class="l-box">
                    <h3>Step 3: View the Data</h3>
                    <p>
                        The best part! View the pretty graphs and statistics of the contest you just hosted and learn from it! 
                    </p>
                </div>
            </div>
        </div>

        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box ribbon">
                    <h2>Interested?</h2>
                    <a href="#" class="pure-button primary-button">Start Your Own Contest</a>
                </div>
            </div>
        </div>
    </div>

    <div class="footer pure-u-1">
        &copy; WishPanda 2013
    </div>
</div>

<script src="http://yui.yahooapis.com/3.10.1/build/yui/yui-min.js"></script>
// <script>
// YUI().use('node-base', 'node-event-delegate', function (Y) {
//     // This just makes sure that the href="#" attached to the <a> elements
//     // don't scroll you back up the page.
//     Y.one('.content').delegate('click', function (e) {
//         e.preventDefault();
//     }, 'a[href="#"]');
// });
// </script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
    <div class="header pure-u-1">
        <div class="pure-menu pure-menu-open pure-menu-horizontal">
            <a class="pure-menu-heading" href="">WishPanda</a>

            <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Contests", contests_path %></li>
                <li><%= link_to "Create a Contest", new_contest_path%></li>
                <li><a href="#">Winners</a></li>
                <li><a href="#">Stats</a></li>
            </ul>
            <ul style="float:right;">  
              <% if user_signed_in? %>
                <li>
                Logged in as <%= current_user.name %>
                </li>
                <li>
                <%= link_to 'Logout', signout_path %>
                </li>
              <% else %>
                <li>
                <%= link_to 'Login', signin_path %>
                </li>
              <% end %>
          </ul>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wishpanda3" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wishpanda3" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :tweet_text %><br />
    <%= f.text_area :tweet_text %>
  </div>
  <div class="field">
    <%= f.label :screen_name %><br />
    <%= f.text_field :screen_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>User</th>
    <th>Tweet text</th>
    <th>Screen name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.user_id %></td>
    <td><%= tweet.tweet_text %></td>
    <td><%= tweet.screen_name %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @tweet.user_id %>
</p>

<p>
  <b>Tweet text:</b>
  <%= @tweet.tweet_text %>
</p>

<p>
  <b>Screen name:</b>
  <%= @tweet.screen_name %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Sign in" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p><%= image_tag @user.picture %> 
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>